feat: gatsby-ify
effectsjs/effectsjs pull request #13
Opened 2020-02-27 08:50 UTC by cdaringe

# problemo

- lots of window hacks in this beautiful, simple, fast jade impl

# solution

- proper compile phase for static site via gatsby... which also has a few hacks up its sleeve

2020-02-27 17:20 UTC, cdaringe commented on packages/effects-docs/.gitignore
> +src/highlight/**/*md
pruning. should no longer be needed

2020-02-27 17:20 UTC, cdaringe commented on packages/effects-docs/.gitignore
> +yarn-error.log*
why was *.log insufficient? pruning.

2020-02-27 17:20 UTC, cdaringe commented on .eslintrc.js
> +    "**/node_modules/**",
was this necessary? 🤔

2020-02-27 17:21 UTC, cdaringe commented on package.json
> +    "format:dryrun": "prettier './*.{js,ts}' './packages/**/*.{js,ts}'",
previously was using shell expansion. whoops

2020-02-27 17:22 UTC, cdaringe commented on packages/effects-docs/gatsby-node.js
> +      regex: "/examples/.*.example$/"
even if something _isnt required_--gatsby tries to parse it.  v. obnoxious--forced me to write. `x.js` files as `x.js.example`

2020-02-27 17:23 UTC, cdaringe commented on packages/effects-docs/gatsby-node.js
> +      regex: "/examples/.*.example$/"
...due to effects.  i _guess_ i could wire gatsby's babel to _our_ babel 🤔 . another time.

2020-02-27 17:24 UTC, cdaringe commented on packages/effects-docs/scripts/reduce-highlight.js
> +go();
without this, highlight.js is quite expensive.  turn off other language packs!

2020-02-27 17:26 UTC, cdaringe commented on packages/effects-docs/src/components/editor.js
> +    // so filter during
incomplete sentence

2020-02-27 17:27 UTC, cdaringe commented on packages/effects-docs/src/util/window-location.js
> +function getWindow() {
for ssr gatsby stuff. will label

2020-02-28 04:39 UTC, dpchamps requested changes

2020-02-28 04:39 UTC, dpchamps commented on packages/effects-docs/src/components/editor.js
> +          <script src="/effectsjs/babel.js"></script>
```suggestion
         <script src={process.env.NODE_ENV === 'development' ? '/babel.js' : '/effectsjs/babel.js'}></script>
```

lame i know

2020-02-28 05:07 UTC, dpchamps approved these changes
💪💪💪💪💪

2020-02-28 05:13 UTC, cdaringe commented on packages/effects-docs/src/pages/examples.js
> +                  to={`/examples/${withoutExampleSuffix(
AND THIS lack of `/` was what was causing the warning message from gatsby's dev runtime.

2020-02-28 06:13 UTC, merged